language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: i+7jew9B4HXKX8OJE/4+asvGVwx06QH9yodwgk1IxafAnfedLT/9cToai35M3liZHnfdcrxSx9JgMqCQ95z6rKWh1wHikBcFe1Snanb0KDvmQgwnnAbDZ9SUP+BMUbQu14UMCkvkuzCDRJ41AMIWUq5KkWaWSyXWorabvS/e7wzeTQnrf8IlMqN1M7jk7v5TD/2tuazZ+NrtUiQBH6zrkAL4YyRVt3vXDM3esyuFMxu7xayxX+TINRqm1Ew+K5st2QFBhMS05krPWB1hUl4H5GdnOZ+nsOC3Xltopd8AMys44P0NcwX9qs0Km/0nWvnJCmrXbrVOeYKb+IAnbtQACQSVXe1EDyRkh3qR4lzcQ8DhrO94wXsuxypR676n8nJnTdmYvccYKGeO/NnEiTGUfcuj9r45Z7SH6VRWkrmsNi8c/D3RCiPft7oWz/vemWOiBiQQgacpx2nbzUVhgSs1TpzGefMiZCNCq8gSpd8/PL50646tATy3JmUpMr2NZu54DQ+t7uFEuXxOjKnYqjsXpBnRaYvBHpYx7TDJvNGeacvXA2GuApl9zHzbD162rBtXeqP0yBtCu74l0ZSc7YKlkHOoi7u7fEc75jN2DzLW32Kb0Z5Pqa2Klaq8LBP/8WN9XzyN2KdM+YACvKlfbHa1+eQHBoL4aWoxmnevOHIlQzU=
